etl_person:
  source:
    type: file
    format: [csv, json, xml]
    location: ../data/
  transformation:
    height:
      unit: meters
      precision: 2
    weight:
      unit: kilograms
      precision: 2
  target:
    type: file
    location: ../data/transformed_data.csv
  logging:
    location: ../data/log_file.txt

etl_car:
  source:
    type: file
    format: [csv, json, xml]
    location: ../data_car/
  transformation:
    price:
      precision: 2
  target:
    type: file
    location: ../data_car/transformed_data.csv
  logging:
    location: ../data_car/log_file.txt

etl_webscrape_movies:
  source:
    type: web
    url: https://web.archive.org/web/20230902185655/https://en.everybodywiki.com/100_Most_Highly-Ranked_Films
    db_name: films
    table_name: Top_50
    location: ../data_scrapeMovies/top_50_films.csv

etl_gdp:
  source:
    type: web
    url: https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29
    db_name: world_economies
    table_name: countries_by_gdp
    table_attribs: ['Country', 'GDP_USD_billions']
    location: ../data_gdp/countries_by_gdp.csv
  logging:
    location: ../data_gdp/log_file.txt
etl_bank:
  source:
    type: web
    url : https://web.archive.org/web/20230908091635 /https://en.wikipedia.org/wiki/List_of_largest_banks
    db_name : Banks
    table_name : Largest_banks
    table_attribs : ['Name', 'MC_USD_Billion']
    location : ../data_bank/exchange_rate.csv
  logging:
    location : ../data_bank/log_file.txt
  output:
    location : ../output/largest_banks_data.csv

settings:
  python_version: "3.8+"
  dependencies:
    - requirements.txt

