on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint pytest-cov
        pip install -r requirements.txt
        
    - name: Set working directory
      run: cd /home/runner/work/
    
    - name: Create necessary directories
      run: |
        mkdir -p output
        mkdir -p data_car
        
    - name: Lint with pylint
      run: |
        pylint src/*.py
    
    - name: Unit Test
      run: |
        python tests/test_etl_car.py
        python tests/test_etl_person.py
