name : CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint pytest-cov
        pip install -r requirements.txt
        
    - name: Lint with pylint
      run: |
        pylint src/*.py
        
    - name: Test with pytest
      run: |
        pytest --cov=src src/*.py
        
    - name: Generate coverage report
      run: |
        pytest --cov=src --cov-report=xml src/*.py 